name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-pass:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Repository sanity
      run: |
        test -f README.md
        test -f Makefile
        test -d src
        test -d include
        echo "CI pass"
